### PR TITLE
Controller Events

### PR DESCRIPTION
**Pull request by robnewton**
Added controller events

### CODE REVIEW

**Comment by robnewton** [comment]
Not sure what that conflict is saying. Maybe you can figure it out.

**Comment by BenWoodford** [comment]
Just git being a jackass and not merging something easy. Shall look at this later thanks.

**Comment by BenWoodford** [comment]
Is this stable and ready for commit now?

**Comment by robnewton** [comment]
It is stable but it could still use some tweaks to improve it.

Rob

**Comment by BenWoodford** [comment]
Good enough, shall finally merge this :P

**Pull request merged**
